version: '3'
services:
  # MongoDB Service
  mongo:
    image: mongo:6.0
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

  # Backend (Node.js API) Service
  backend:
    build:
      context: ./backend  # Path to the backend directory
    ports:
      - "8888:8888"  # Map the backend port
    volumes:
      - ./backend:/app  # Sync backend code to /app in the container
    environment:
      DATABASE: "mongodb+srv://development:PUvFHsb3l47Ez524@cluster0.c5cjb.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0"
      PORT: 8888
      JWT_SECRET: "your_private_jwt_secret_key"
      NODE_ENV: "production"
      OPENSSL_CONF: '/dev/null'
      PUBLIC_SERVER_FILE: "http://localhost:8888/"
      WEB_URL: "http://localhost:3001"

  # Frontend (React.js) Service
  frontend:
    build:
      context: ./frontend  # Path to the frontend directory
    ports:
      - "3001:3001"  # Map the frontend port
    volumes:
      - ./frontend:/app  # Sync frontend code to /app in the container
    environment:
      VITE_FILE_BASE_URL: "http://localhost:8888/"
      VITE_BACKEND_SERVER: "http://localhost:8888/"

volumes:
  mongo-data:  # Volume for MongoDB data